---
title: "project_classificication"
author: "Sara Altman"
date: "11/16/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}

```

```{r}
library(tidyverse)
library(glmnet)
library(modelr)
```

```{r, message=FALSE}
#got approval to use entire dataset, so we're not splitting into test and train
by_subj <- read_csv("../data/relapse_subjects.csv", na = c("", "NaN"))
```

```{r}
is_zero <- function(x) all(mean(x^2) == 0)

vars_no_nas <-
  by_subj %>% 
  summarise_all(function(x) {mean(is.na(x))}) %>% 
  select_if(is_zero) %>% 
  select(-obstime, 
         -starts_with("mpfc"), 
         -starts_with("vta"), 
         -starts_with("acing"), 
         -starts_with("ains"),
         -ends_with("mean"),
         -censored
        # -ends_with("beta")
         ) %>% 
  colnames()

by_subj_no_nas <-
  by_subj %>% 
  select(vars_no_nas)

#this does cross-validates lasso. alpha = 1 specifies that we want lasso. type.measure = class specifies we're doing classification. for regression, just use default (same for family)
lasso_ind <- cv.glmnet(x = by_subj_no_nas %>% select(-subjid, -relIn6Mos) %>%  data.matrix, 
                y = by_subj_no_nas$relIn6Mos, 
                alpha = 1,
                type.measure = "class",
                family = "binomial")

lasso_coefs <- coef(lasso_ind, s = lasso_ind$lambda.1se)
min(lasso_ind$cvm)
lasso_coefs
```

```{r}
test_err <- function(test, mod) {
  test <- as_tibble(test)
  
  errors <- 
    test %>% 
    mutate(
      pred = predict(mod, newdata = test, type = "response"),
      pred_group = ifelse(pred > .4, 1, 0),
      pred_error = ifelse(relIn6Mos != pred_group, 1, 0)
    )
  
  mean(errors$pred_error)
}

by_subj_cv <-
  by_subj %>% 
  crossv_kfold(31)

by_subj_cv %>% 
  mutate(train = map(train, as_tibble),
         model = map(train, ~glm(relIn6Mos ~ #age + 
                                  #nacc_drugs_TR6 +
                                  #nacc_drugs_beta +
                                  #vta_drugs_TR6 +
                                  nacc_neutral_beta,
                                  #censored,
                                  #nacc_neutral_TR5,
                                  #lambda = #find via cross validation
                                  family = binomial, 
                                  data = .)),
         error = map2_dbl(test, model, test_err)) %>% 
  summarise(mean(error))
```

